# Generated by Django 5.0.1 on 2026-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0004_seed_tips_galeri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'ordering': ['-dibuat'], 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterField(
            model_name='galeri',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
    ]
