# Generated by Django 5.0.1 on 2026-06-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuaca', '0008_delete_favoritkota'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='balasan_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
